frontend:
  image: node:14.15.0
  command: bash -c "npm i && npm run build && npm run generate && npm start"
  volumes:
    - ./:/usr/src/app
  working_dir: /usr/src/app
  ports:
    - "3000:3000"
  environment:
    HOST: 0.0.0.0